[package]
name = "pcap-to-json"
version = "0.1.0"
edition = "2024"

[dependencies]
pcap = "1"                                          # Read PCAP files
serde = { version = "1", features = ["derive"] }    # JSON serialization
serde_json = "1"                                    # JSON output